# Master playbook
# Notes:
# - Taints are applied only after monitoring tools have been installed on the pods.

# Console
- import_playbook: playbooks/console.yml  # Basic setup on console machine
- import_playbook: playbooks/nginx.yml # Setting nginx in advance so that Keycloak etc. can be tested 
- import_playbook: playbooks/nfs.yml 
# MZ cluster
- import_playbook: playbooks/mzcluster.yml
- import_playbook: playbooks/mzmonitoring.yml
- import_playbook: 
