{{- if .Values.persistence.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mediawiki.claimname" . }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end -}}
{{- if .Values.backups.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mediawiki.fullname" . }}-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.backups.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.backups.size }}
{{- end -}}
