---
apiVersion: v1
metadata:
  name: {{ template "mediawiki.fullname" . }}-imagepull-secrets
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "mediawiki.imagePullSecret" . }}
kind: Secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
metadata:
  name: {{ template "mediawiki.fullname" . }}-migration
  labels:
    migration-config: "true"
data:
  # Cg== = "" base encoded, but doing that with the b64enc function returns nothing,
  # causing an error
  username: {{ if .Values.migration.user }}{{ .Values.migration.user | b64enc }}{{- else -}}Cg=={{- end }}
  password: {{ if .Values.migration.password }}{{ .Values.migration.password | b64enc }}{{- else -}}Cg=={{- end }}
kind: Secret
type: Opaque
---
apiVersion: v1
metadata:
  name: {{ template "mediawiki.fullname" . }}-my-secrets
data:
{{- if .Values.mediawiki.wgDBAdminPassword }}
  admin.cnf: {{ printf "[client]\nuser=root\npassword=%s\n" .Values.mediawiki.wgDBAdminPassword | b64enc }}
{{- else }}
  admin.cnf: {{ printf "[client]\nuser=root\n" | b64enc }}
{{- end }}

{{- if .Values.mediawiki.wgDBPassword }}
  mediawiki.cnf: {{ printf "[client]\nuser=%s\npassword=%s\n" .Values.mediawiki.wgDBUser .Values.mediawiki.wgDBPassword | b64enc }}
{{- else }}
  mediawiki.cnf: {{ printf "[client]\nuser=%s\n" .Values.mediawiki.wgDBUser | b64enc }}
{{- end }}
kind: Secret
type: Opaque
---
apiVersion: v1
metadata:
  name: {{ template "mediawiki.fullname" . }}-password-secrets
data:
  db-admin-password: {{ .Values.mediawiki.wgDBAdminPassword | b64enc }}
  db-wiki-password: {{ .Values.mediawiki.wgDBPassword | b64enc }}
  admin-password: {{ .Values.mediawiki.adminPassword | b64enc }}
  {{- if .Values.gitToken }}git-token:{{ .Values.gitToken | b64enc }}{{- else }}{{- end }}
  backups-password: {{ template "mediawiki.backupHtpasswd" . }}
kind: Secret
type: Opaque
